bike/urls.py
from django.urls import path

from .views import IndexView, bike, refueling, maintenance

app_name = 'bike'
urlpatterns = [
    path("", IndexView.as_view(), name="bikeIndex"),
    path("refueling/", refueling.ListView.as_view(), name="refuelingList"),
    path("refueling/<int:pk>/details/", refueling.DetailView.as_view(), name="refuelingDetail"),
    path("refueling/<int:pk>/delete/", refueling.DeleteView.as_view(), name='refuelingDelete'),
    path("refueling/<int:pk>/edit/", refueling.UpdateView.as_view(), name="refuelingUpdate"),
    path("refueling/addRefueling/", refueling.CreateView.as_view(), name="refuelingCreate"),
    path("bikes", bike.ListView.as_view(), name="bikeList"),
    path("bikes/<int:pk>/details/", bike.DetailView.as_view(), name="bikeDetail"),
    path("bikes/<int:pk>/delete/", bike.DeleteView.as_view(), name='bikeDelete'),
    path("bikes/<int:pk>/edit/", bike.UpdateView.as_view(), name="bikeUpdate"),
    path("bikes/addBike", bike.CreateView.as_view(), name="bikeCreate"),
    path("maintenance", maintenance.ListView.as_view(), name="maintenanceList"),
    path("maintenance/<int:pk>/details/", maintenance.DetailView.as_view(), name="maintenanceDetail"),
    path("maintenance/<int:pk>/delete/", maintenance.DeleteView.as_view(), name='maintenanceDelete'),
    path("maintenance/<int:pk>/edit/", maintenance.UpdateView.as_view(), name="maintenanceUpdate"),
    path("maintenance/addBike", maintenance.CreateView.as_view(), name="maintenanceCreate"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('temp/', include('temp.urls')),
    path('bike/', include('bike.urls')),
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('bike/')),
]

bike/models.py
from unicodedata import decimal
from django.db import models
from django.urls import reverse_lazy


class Fuel(models.Model):
    bike = models.ForeignKey("Bike", models.CASCADE)
    fuel_date = models.DateTimeField('date fueled up')
    quantity = models.DecimalField('Amount fueled up', max_digits=5, decimal_places=2)
    cost_per_litre = models.DecimalField('Cost per litre', max_digits=5, decimal_places=3)
    total_cost = models.DecimalField('Total cost of fueling', max_digits=5, decimal_places=2)
    km_trip = models.IntegerField('Km since last fueling')
    km_total = models.IntegerField('Total Km of the bike')

    def __str__(self) -> str:
        return "Fueling on {}: {}€".format(self.fuel_date, self.total_cost)

    def litre_per_100km(self) -> decimal:
        return self.quantity / self.km_trip * 100

    def get_absolute_url(self):
        return reverse_lazy("bike:refuelingDetail", kwargs={"pk": self.id})


class Maintenance(models.Model):
    bike = models.ForeignKey("Bike", models.CASCADE)
    date = models.DateField('Date of maintenance work')
    maintenance_type = models.ForeignKey("MaintenanceType", models.CASCADE)
    cost = models.DecimalField('Total cost of maintenance', max_digits=3, decimal_places=2)

    def __str__(self) -> str:
        return "{} done on {}".format(self.maintenance_type, self.date)


class MaintenanceType(models.Model):
    name = models.CharField('Name', max_length=30)


class Bike(models.Model):
    ID = models.IntegerField("ID", primary_key=True)
    name = models.CharField('Name', max_length=30)
    manufacturer = models.CharField('Manufacturer', max_length=30)
    initial_odometer = models.IntegerField("Initial Odometer Reading", default=0)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("bike:bikeDetail", kwargs={"pk": self.ID})

bike/views/bike.py
from django.views import generic
from django.urls import reverse_lazy
from ..models import Bike

bike_fields = ["name", "manufacturer", "initial_odometer"]


class ListView(generic.ListView):
    template_name = 'bike/bike_list.html'
    context_object_name = 'bike_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "bikes"
        return context

    def get_queryset(self):
        return Bike.objects.all()


class DetailView(generic.DetailView):
    model = Bike
    template_name = 'bike/bike_detail.html'
    fields = bike_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "bikes"
        return context


class CreateView(generic.CreateView):
    model = Bike
    template_name = 'bike/t_create.html'
    fields = bike_fields
    success_url = reverse_lazy("bike:bikeList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "bikes"
        context['title'] = "Add Bike"
        context['header'] = "Add a new Bike"
        return context


class DeleteView(generic.DeleteView):
    model = Bike
    template_name_suffix = "_delete"
    success_url = reverse_lazy("bike:bikeList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "bikes"
        context['title'] = "Delete Bike"
        context['header'] = "Delete the Bike?"
        return context


class UpdateView(generic.UpdateView):
    model = Bike
    template_name = "bike/t_update.html"
    fields = bike_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "bikes"
        context['title'] = "Edit Bike"
        context['header'] = "Edit the Bike:"
        return context

bike/views/maintenance.py
from django.forms import DateInput
from django.views import generic
from django.urls import reverse_lazy
from django_filters.views import FilterView
import django_filters as dj_filters

from ..models import Maintenance
from ..plots import fuel_economy, fuel_price, fuel_odometer

maintenance_fields = ["bike", "date", "maintenance_type", "cost"]


class DateWidget(DateInput):
    input_type = "date"


class MaintenanceFilter(dj_filters.FilterSet):
    date__gt = dj_filters.DateTimeFilter(field_name="date", lookup_expr='gt',
                                         label="From", widget=DateWidget)
    date__lt = dj_filters.DateTimeFilter(field_name="date", lookup_expr='lt',
                                         label="Till", widget=DateWidget)

    class Meta:
        model = Maintenance
        fields = ['bike']


class ListView(FilterView):
    model = Maintenance
    template_name = 'bike/maintenance_list.html'
    context_object_name = 'maintenance_list'
    filterset_class = MaintenanceFilter
    showClear = False

    def get(self, request, *args, **kwargs):
        self.showClear = any(field in request.GET for field in
                             set(self.filterset_class.get_fields()))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "maintenance"
        if self.showClear:
            context['display_clear'] = "true"
        return context


class DetailView(generic.DetailView):
    model = Maintenance
    template_name = "bike/maintenance_detail.html"
    fields = maintenance_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "maintenance"
        return context

    def get_queryset(self):
        return Maintenance.objects.all()


class CreateView(generic.CreateView):
    model = Maintenance
    template_name = 'bike/t_create.html'
    fields = maintenance_fields
    success_url = reverse_lazy("bike:maintenanceList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "maintenance"
        context['title'] = "Create Maintenance"
        context['header'] = "Create a new Maintenance Entry:"
        return context


class DeleteView(generic.DeleteView):
    model = Maintenance
    template_name = "bike/t_delete.html"
    success_url = reverse_lazy("bike:maintenanceList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "maintenance"
        context['title'] = "Delete Maintenance"
        context['header'] = "Delete the Maintenance Entry?"
        return context


class UpdateView(generic.UpdateView):
    model = Maintenance
    template_name = "bike/t_update.html"
    fields = maintenance_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "Maintenance"
        context['title'] = "Edit Maintenance"
        context['header'] = "Edit the Maintenance Entry:"
        return context

bike/views/refueling.py
from django.forms import DateTimeInput
from django.views import generic
from django.urls import reverse_lazy
from django_filters.views import FilterView
import django_filters as dj_filters

from ..models import Fuel
from ..plots import fuel_economy, fuel_price, fuel_odometer

refueling_fields = ["bike", "fuel_date", "quantity", "cost_per_litre", "total_cost", "km_trip", "km_total"]


class DateTimeWidget(DateTimeInput):
    input_type = "datetime-local"


class RefuelingFilter(dj_filters.FilterSet):
    fuel_date__gt = dj_filters.DateTimeFilter(field_name="fuel_date", lookup_expr='gt',
                                              label="From", widget=DateTimeWidget)
    fuel_date__lt = dj_filters.DateTimeFilter(field_name="fuel_date", lookup_expr='lt',
                                              label="Till", widget=DateTimeWidget)

    class Meta:
        model = Fuel
        fields = ['bike']


class ListView(FilterView):
    model = Fuel
    template_name = 'bike/refueling_list.html'
    context_object_name = 'fueling_list'
    filterset_class = RefuelingFilter
    showClear = False

    def get(self, request, *args, **kwargs):
        self.showClear = any(field in request.GET for field in
                             set(self.filterset_class.get_fields()))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "refueling"
        if self.showClear:
            context['display_clear'] = "true"
        if len(context['object_list']) > 0:
            context['plot_1'] = fuel_economy(context['object_list'])
            context['plot_2'] = fuel_price(context['object_list'])
            context['plot_3'] = fuel_odometer(context['object_list'])
        return context


class DetailView(generic.DetailView):
    model = Fuel
    template_name = "bike/refueling_detail.html"
    fields = refueling_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "refueling"
        return context

    def get_queryset(self):
        return Fuel.objects.all()


class CreateView(generic.CreateView):
    model = Fuel
    template_name = 'bike/t_create.html'
    fields = refueling_fields
    success_url = reverse_lazy("bike:refuelingList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "refueling"
        context['title'] = "Add Refueling"
        context['header'] = "Add a new Refueling"
        return context


class DeleteView(generic.DeleteView):
    model = Fuel
    template_name = "bike/t_delete.html"
    success_url = reverse_lazy("bike:refuelingList")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "refueling"
        context['title'] = "Delete Refueling"
        context['header'] = "Delete the Refueling?"
        return context


class UpdateView(generic.UpdateView):
    model = Fuel
    template_name = "bike/t_update.html"
    fields = refueling_fields

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navigationbar_active'] = "refueling"
        context['title'] = "Edit Refueling"
        context['header'] = "Edit Refueling:"
        return context

bike/templates/bike/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bike/styles.css' %}">
    <base href="{% static '/' %}">
    <title>{% block title %}Bike Statistics{% endblock %}</title>
</head>

<body>
    <header>
        <nav>
            <ul class="navbar">
                <li><a {% if navigationbar_active == "home" %}class="active"{% endif %} href="{% url 'bike:bikeIndex' %}">Home</a></li>
                <li><a {% if navigationbar_active == "bikes" %}class="active"{% endif %} href="{% url 'bike:bikeList' %}">Bikes</a></li>
                <li><a {% if navigationbar_active == "refueling" %}class="active"{% endif %} href="{% url 'bike:refuelingList' %}">Refueling</a></li>
                <li><a {% if navigationbar_active == "maintenance" %}class="active"{% endif %} href="{% url 'bike:maintenanceList' %}">Maintenance</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}
    <p>
        Your Content should be displayed here.
    </p>
    {% endblock %}
</body>
</html>

bike/templates/bike/bike_detail.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Bike Detail{% endblock %}

{% block content %}
{% if bike %}
    <h1>{{ bike.name }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <p>Manufactuerer: {{ bike.manufacturer }}</p>
            <p>Initial Odometer: {{ bike.initial_odometer }}</p>
            <button type="button" onclick="window.location.href='{% url 'bike:bikeUpdate' bike.ID %}';">Edit</button>
            <button type="button" onclick="window.location.href='{% url 'bike:bikeDelete' bike.ID %}';">Delete</button>
        </div>
    </div>
{% else %}
    <h1>Bike Details</h1>
    <p> Bike Not Found </p>
{% endif %}
{% endblock %}

bike/templates/bike/bike_form.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>AddBike</title>
    <link rel="stylesheet" href="{% static 'bike/styles.css' %}">
</head>
<body>
<h1> Add a new Bike </h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

bike/templates/bike/bike_list.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Bikes{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center">
        <h1>Bikes</h1>
        <div style="margin-left: auto">
            <button type="button" onclick="window.location.href='{% url 'bike:bikeCreate' %}';">Add Bike</button>
        </div>
    </div>
    {% if bike_list %}
        <div class="boxBody">
            <div class="itemBox">
                <ul>
                    {% for bike in bike_list %}
                        <li><a href= {% url 'bike:bikeDetail' bike.ID %} >{{ bike.manufacturer }}  {{ bike.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <p>No bikes are available.</p>
    {% endif %}
{% endblock %}

bike/templates/bike/index.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Bike Statistics Home {% endblock %}

{% block content %}
<h1>Bike Statistics Home</h1>
<div class="boxBody">
    <div class="itemBox">
        <p>First Item</p>
        <ul>
            <li>First</li>
            <li>Second</li>
            <li>Third</li>
        </ul>
    </div>
    <div class="itemBox">
        <p>Hier könnte ihre werbung stehen</p>
    </div>
</div>
{% endblock %}

bike/templates/bike/maintenance_detail.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Maintenance{% endblock %}

{% block content %}
{% if fuel %}
    <h1>{{ fuel }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <p>Bike: {{ maintenance.bike }}</p>
            <p>Date: {{ maintenance.date }}</p>
            <p>Type: {{ maintenance.maintenance_type }}</p>
            <p>Cost: {{ maintenance.cost }}</p>
            <button type="button" onclick="window.location.href='{% url 'bike:maintenanceUpdate' fuel.id %}';">Edit</button>
            <button type="button" onclick="window.location.href='{% url 'bike:maintenanceDelete' fuel.id %}';">Delete</button>
        </div>
    </div>
{% else %}
    <h1>Maintenance Detail</h1>
    <div class="boxBody">
        <div class="itemBox">
            <p> Maintenance Not Found </p>
        </div>
    </div>
{% endif %}
{% endblock %}

bike/templates/bike/maintenance_list.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Maintenance{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center">
        <h1>Maintenance Statistics</h1>
        <div style="margin-left: auto">
            <button type="button" onclick="window.location.href='{% url 'bike:maintenanceCreate' %}';">Add Maintenance</button>
            <button type="button" onclick="toggleVisible('filterBox')">Filter</button>
        </div>
    </div>
    <div class="boxBody">
        <div class="itemBox" id="filterBox">
            <h2>Filter</h2>
            <form action="" method="get">
                {{ filter.form.as_p}}
                <div style="display: flex;">
                    <p style="margin-left: auto">
                        {% if display_clear %}
                            <input type="button" value="Clear" style="margin-left: unset;"
                                   onclick="window.location.href='{% url 'bike:maintenanceList' %}';"/>
                        {% endif %}
                        <input type="submit" style="margin-left: 20px;"/>
                    </p>
                </div>
            </form>
        </div>

        {% if maintenance_list %}
            <div class="itemBox">
                <h2>Refueling List</h2>
                <ul>
                    {% for maintenance in maintenance_list %}
                        <li><a href={% url 'bike:maintenanceDetail' maintenance.id %}>{{ maintenance_list }}</a></li>
                    {% endfor %}
                </ul>
            </div>

        {% else %}
            <div class="itemBox">
                <p>No maintenance entries available!</p>
                <p>If set, please try to adjust the filter to get more items.</p>
                <p>Otherwise try <a href={% url 'bike:maintenanceCreate' %}>adding</a> more maintenance entries.</p>
            </div>
        {% endif %}
    </div>
    <script>
        function toggleVisible(elemID, displayType = "block") {
            let elem = document.getElementById(elemID);
            if (elem.style.display === "none") {
                elem.style.display = displayType;
            } else {
                elem.style.display = "none";
            }
        }
    </script>
{% endblock %}

bike/templates/bike/refueling_detail.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Refueling{% endblock %}

{% block content %}
{% if fuel %}
    <h1>{{ fuel }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <p>Fueling Date: {{ fuel.fuel_date }}</p>
            <p>Quantity: {{ fuel.quantity }}L </p>
            <p>Cost: {{ fuel.cost_per_litre }}€/L</p>
            <p>Total: {{ fuel.total_cost }}€</p>
            <p>Trip: {{ fuel.km_trip }}km</p>
            <p>Odometer Reading: {{ fuel.km_total }}km</p>
            <p>Bike: {{ fuel.bike }}</p>
            <button type="button" onclick="window.location.href='{% url 'bike:refuelingUpdate' fuel.id %}';">Edit</button>
            <button type="button" onclick="window.location.href='{% url 'bike:refuelingDelete' fuel.id %}';">Delete</button>
        </div>
    </div>
{% else %}
    <h1>Refueling Detail</h1>
    <div class="boxBody">
        <div class="itemBox">
            <p> Refueling Not Found </p>
        </div>
    </div>
{% endif %}
{% endblock %}

bike/templates/bike/refueling_list.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}Refueling{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center">
        <h1>Refueling Statistics</h1>
        <div style="margin-left: auto">
            <button type="button" onclick="window.location.href='{% url 'bike:refuelingCreate' %}';">Add Refueling</button>
            <button type="button" onclick="toggleVisible('filterBox')">Filter</button>
        </div>
    </div>
    <div class="boxBody">
        <div class="itemBox" id="filterBox">
            <h2>Filter</h2>
            <form action="" method="get">
                {{ filter.form.as_p}}
                <div style="display: flex;">
                    <p style="margin-left: auto">
                        {% if display_clear %}
                            <input type="button" value="Clear" style="margin-left: unset;"
                                   onclick="window.location.href='{% url 'bike:refuelingList' %}';"/>
                        {% endif %}
                        <input type="submit" style="margin-left: 20px;"/>
                    </p>
                </div>
            </form>
        </div>

        {% if fueling_list %}
            <div class="itemBox">
                <h2>Refueling List</h2>
                <ul>
                    {% for fueling in fueling_list %}
                        <li><a href={% url 'bike:refuelingDetail' fueling.id %}>Fueling on {{ fueling.fuel_date }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="itemBox">
                <h2>Plot:</h2>
                <label for="plotSelect">Select Figure:</label>
                <select name="plots" id="plotSelect"
                        onchange="selectPlot(this.value)">
                    <option selected="selected">Fuel Economy</option>
                    <option>Fuel Prices</option>
                    <option>Odometer</option>
                </select>
                {% autoescape off %}
                    <div id="plot_1">
                        {{ plot_1 }}
                    </div>
                    <div id="plot_2" style="display: none">
                        {{ plot_2 }}
                    </div>
                    <div id="plot_3" style="display: none">
                        {{ plot_3 }}
                    </div>
                {% endautoescape %}
            </div>
        {% else %}
            <div class="itemBox">
                <p>No refueling entries available!</p>
                <p>If set, please try to adjust the filter to get more items.</p>
                <p>Otherwise try <a href={% url 'bike:refuelingCreate' %}>adding</a> more refueling entries.</p>
            </div>
        {% endif %}
    </div>
    <script>
        function toggleVisible(elemID, displayType = "block") {
            let elem = document.getElementById(elemID);
            if (elem.style.display === "none") {
                elem.style.display = displayType;
            } else {
                elem.style.display = "none";
            }
        }

        function selectPlot(plot) {
            let plots = {
                "Fuel Economy": "plot_1",
                "Fuel Prices": "plot_2",
                "Odometer": "plot_3",
            }
            let plot_num = 3
            for(let ii = 1; ii <= plot_num; ii += 1) {
                let elem = document.getElementById("plot_"+ii)
                elem.style.display = "none";
            }
            let elem = document.getElementById(plots[plot])
            elem.style.display = "block";
        }
    </script>
{% endblock %}

bike/templates/bike/t_create.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ header }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

bike/templates/bike/t_delete.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ header }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input type="submit" value="Confirm">
            </form>
        </div>
    </div>
{% endblock %}

bike/templates/bike/t_update.html
{% extends "bike/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'bike/styles.css' %}">

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ header }}</h1>
    <div class="boxBody">
        <div class="itemBox">
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update">
            </form>
        </div>
    </div>
{% endblock %}